# Your app credentials. These will be used to authenticate in Telegram. (https://core.telegram.org/api/obtaining_api_id)
api_id: 12345678
api_hash: 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6'
# Default Discord Webhook URL, if it isn't specified in channel_ids. (https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks)
discord_webhook_url: 'https://discord.com/api/webhooks/channelID/webhookID'

# Channels that you'd like to forward messages from. User running the client must have these channels present on its dialogs.
# Input singlular or multiple Telegram channel IDs here. Make sure to use Telegram API specifically, and not Bot API!
# You can get them by enabling experimental "Show Peer IDs" setting in desktop.
channel_ids:
  {
    1234567890, # uncpecified webhook, will use default
    2345678901: 'https://discord.com/api/webhooks/channelID/webhookID' # will send messages to specified webhook
  }
